version: '3'

services:
  # Open WebUI service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=true
      # Keycloak Configuration
      - KEYCLOAK_ENABLED=true
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=open-webui
      - KEYCLOAK_CLIENT_ID=open-webui-client
      - KEYCLOAK_CLIENT_SECRET=WWcJRGPJBUS6qIhhED8fZelh7FL0t1ne
      - KEYCLOAK_REDIRECT_URI=http://localhost:8080/oauth/keycloak/callback
      # OAuth Configuration
      - OPENID_PROVIDER_URL=http://keycloak:8080/realms/open-webui/.well-known/openid-configuration
      - OAUTH_CLIENT_ID=open-webui-client
      - OAUTH_CLIENT_SECRET=WWcJRGPJBUS6qIhhED8fZelh7FL0t1ne
      - OPENID_REDIRECT_URI=http://localhost:8080/oauth/oidc/callback
      - OAUTH_PROVIDER_NAME=Keycloak
      - OAUTH_SCOPES=openid email profile
      - OAUTH_EMAIL_CLAIM=email
      - OAUTH_USERNAME_CLAIM=preferred_username
      - OAUTH_PICTURE_CLAIM=picture
      - OAUTH_ROLES_CLAIM=roles
      - OAUTH_GROUPS_CLAIM=groups
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_OAUTH_ROLE_MANAGEMENT=true
      - ENABLE_OAUTH_GROUP_MANAGEMENT=true
      - OAUTH_ALLOWED_ROLES=user,admin
      - OAUTH_ADMIN_ROLES=admin
    ports:
      - "8080:8080"
    depends_on:
      - ollama
      - keycloak

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

  # Keycloak service
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  # PostgreSQL database for Keycloak
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  open-webui-data:
  ollama-data:
  postgres-data:
