version: '3'

services:
  # Open WebUI service
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=true
      - WEBUI_SESSION_COOKIE_SECURE=false
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      # Keycloak Configuration
      - KEYCLOAK_ENABLED=true
      - KEYCLOAK_SERVER_URL=https://keycloak.pcpldevelopment.com
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=open-webui-client
      - KEYCLOAK_CLIENT_SECRET=1fXnCR1kuFr8OyHcc8LxKA9Q3a9RGjY8
      - KEYCLOAK_REDIRECT_URI=http://localhost:8080/oauth/keycloak/callback
      # OAuth Configuration
      - OPENID_PROVIDER_URL=https://keycloak.pcpldevelopment.com/realms/master/.well-known/openid-configuration
      - OAUTH_CLIENT_ID=open-webui-client
      - OAUTH_CLIENT_SECRET=1fXnCR1kuFr8OyHcc8LxKA9Q3a9RGjY8
      - OPENID_REDIRECT_URI=http://localhost:8080/oauth/oidc/callback
      - OAUTH_PROVIDER_NAME=Keycloak
      - OAUTH_SCOPES=openid email profile
      - OAUTH_EMAIL_CLAIM=email
      - OAUTH_USERNAME_CLAIM=preferred_username
      - OAUTH_PICTURE_CLAIM=picture
      - OAUTH_ROLES_CLAIM=roles
      - OAUTH_GROUPS_CLAIM=groups
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_OAUTH_ROLE_MANAGEMENT=true
      - ENABLE_OAUTH_GROUP_MANAGEMENT=true
      - OAUTH_ALLOWED_ROLES=user,admin
      - OAUTH_ADMIN_ROLES=admin
    ports:
      - "8080:8080"
    depends_on:
      - ollama

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  open-webui-data:
  ollama-data:
